# Generated by Django 5.2.1 on 2025-06-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Bairro',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(choices=[('0', '10ª'), ('1', '11ª'), ('2', '12ª'), ('3', '13ª')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'Classe',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('modalidade', models.CharField(choices=[('P', 'Presencial'), ('O', 'Online'), ('S', 'Semi-presencial')], max_length=1)),
                ('nivel', models.CharField(choices=[('T', 'Técnico'), ('G', 'Graduação'), ('P', 'Pós-graduação')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('idade', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefone', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('numAgente', models.CharField(max_length=25, unique=True)),
                ('tipo_documento', models.CharField(choices=[('D', 'Declaração'), ('C', 'Certificado')], max_length=1)),
            ],
            options={
                'db_table': 'Direitor',
            },
        ),
        migrations.CreateModel(
            name='DiretorAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('idade', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefone', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('numAgente', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'DiretorAdministrativo',
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Especialidade',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Pedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('idade', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefone', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('numAgente', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'Pedagogico',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Provincia',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classe')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=20)),
                ('nif', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=25)),
                ('telefone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('alvara', models.ImageField(blank=True, null=True, upload_to='documentos/')),
                ('ano_fundacao', models.IntegerField()),
                ('tipo_escola', models.CharField(choices=[('P', 'Primária'), ('S', 'Secundária'), ('U', 'Universitária')], max_length=1)),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.bairro')),
                ('direitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.diretor')),
                ('direitor_administrativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.diretoradministrativo')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.municipio')),
                ('direitor_pedagogico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.pedagogico')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.provincia')),
            ],
            options={
                'db_table': 'Escola',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.escola'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('idade', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefone', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('numAgente', models.CharField(max_length=25, unique=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('disciplina', models.ManyToManyField(to='school.disciplina')),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.especialidade')),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1, null=True)),
                ('ano_lectivo', models.CharField(max_length=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classe')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('idade', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefone', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classe')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.turma')),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
    ]
