# Generated by Django 5.1.7 on 2025-06-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='classe',
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'curso', 'classe')},
        ),
    ]
