# Generated by Django 5.1.7 on 2025-06-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_aluno_classe_alter_turma_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diretor',
            name='tipo_documento',
        ),
    ]
