# Generated by Django 5.1.7 on 2025-06-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_diretor_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='diretoradministrativo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='pedagogico',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
    ]
