# Generated by Django 5.1.7 on 2025-06-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_aluno_image_alter_diretor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='alvara',
            field=models.ImageField(blank=True, null=True, upload_to='media/documento/'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo/'),
        ),
    ]
