# Generated by Django 5.2.1 on 2025-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_escola_alvara_alter_escola_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagem'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagem'),
        ),
        migrations.AlterField(
            model_name='diretoradministrativo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagem'),
        ),
        migrations.AlterField(
            model_name='pedagogico',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagem'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagem'),
        ),
    ]
