# Generated by Django 5.1.7 on 2025-06-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_professor_disciplina_professor_disciplina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='matricula',
            new_name='bilhete',
        ),
    ]
