# Generated by Django 5.2.1 on 2025-06-10 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rename_matricula_aluno_bilhete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='diretor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='diretoradministrativo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pedagogico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
    ]
