# Generated by Django 5.2.1 on 2025-06-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_professor_especialidade_professor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diretor',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='diretor',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='diretor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='diretoradministrativo',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='diretoradministrativo',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='diretoradministrativo',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='pedagogico',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='pedagogico',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='pedagogico',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='telefone',
        ),
    ]
