# Generated by Django 5.2.1 on 2025-06-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.departamento'),
        ),
    ]
