# Generated by Django 5.2.1 on 2025-06-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_coordenador_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
