# Generated by Django 5.2.1 on 2025-06-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_disciplina_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('M', 'Manhâ'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1, null=True),
        ),
    ]
