# Generated by Django 5.2.1 on 2025-06-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_turma_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
