# Generated by Django 5.2.1 on 2025-06-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_turma_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='telefone',
        ),
    ]
