# Generated by Django 5.2.1 on 2025-06-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_remove_escola_bairro_remove_escola_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='endereco',
        ),
        migrations.AddField(
            model_name='escola',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.bairro'),
        ),
    ]
