# Generated by Django 5.2.1 on 2025-06-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_remove_escola_endereco_escola_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='alvara',
            field=models.FileField(blank=True, null=True, upload_to='alvara/'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
