# Generated by Django 5.2.1 on 2025-06-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_escola_alvara_alter_escola_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='ano_fundacao',
            field=models.DateField(),
        ),
    ]
