# Generated by Django 5.2.1 on 2025-06-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_escola_ano_fundacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo/'),
        ),
    ]
