# Generated by Django 5.2.1 on 2025-06-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_diretor_user_diretoradministrativo_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre')], max_length=1)),
                ('av1', models.FloatField(blank=True, null=True)),
                ('av2', models.FloatField(blank=True, null=True)),
                ('av3', models.FloatField(blank=True, null=True)),
                ('av4', models.FloatField(blank=True, null=True)),
                ('mac', models.FloatField(blank=True, null=True)),
                ('npp', models.FloatField(blank=True, null=True)),
                ('npt', models.FloatField(blank=True, null=True)),
                ('mt', models.FloatField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.turma')),
            ],
        ),
        migrations.CreateModel(
            name='TrimestreLiberado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º')])),
                ('liberado', models.BooleanField(default=False)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.turma')),
            ],
            options={
                'unique_together': {('turma', 'disciplina', 'trimestre')},
            },
        ),
    ]
