# Generated by Django 5.2.1 on 2025-06-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_minipauta_trimestreliberado'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipauta',
            name='assiduidade',
            field=models.CharField(blank=True, choices=[('Muito Boa', 'Muito Boa'), ('Boa', 'Boa'), ('Razoável', 'Razoável'), ('Fraca', 'Fraca')], max_length=20),
        ),
        migrations.AddField(
            model_name='minipauta',
            name='comportamento',
            field=models.CharField(blank=True, choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Razoável', 'Razoável'), ('Insatisfatório', 'Insatisfatório')], max_length=20),
        ),
        migrations.AddField(
            model_name='minipauta',
            name='faltas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
