# Generated by Django 5.2.1 on 2025-06-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_minipauta_assiduidade_minipauta_comportamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minipauta',
            name='assiduidade',
            field=models.CharField(blank=True, choices=[('M', 'Muito Boa'), ('B', 'Boa'), ('R', 'Razoável'), ('F', 'Fraca')], max_length=20),
        ),
        migrations.AlterField(
            model_name='minipauta',
            name='comportamento',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bom'), ('R', 'Razoável'), ('I', 'Insatisfatório')], max_length=20),
        ),
    ]
