# Generated by Django 5.2.1 on 2025-06-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_alter_minipauta_av1_alter_minipauta_av2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipauta',
            name='exame',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='minipauta',
            name='mf',
            field=models.FloatField(default=0),
        ),
    ]
