# Generated by Django 5.2.1 on 2025-06-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_minipauta_exame_minipauta_mf'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='ciclo',
            field=models.CharField(choices=[('7', '7ª'), ('8', '8ª'), ('9', '9ª')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.escola'),
        ),
        migrations.AddField(
            model_name='classe',
            name='promaria',
            field=models.CharField(choices=[('0', '0ª'), ('1', '1ª'), ('2', '2ª'), ('3', '3ª'), ('4', '4ª'), ('5', '5ª'), ('6', '6ª')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.curso'),
        ),
    ]
