# Generated by Django 5.2.1 on 2025-06-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_classe_ciclo_classe_escola_classe_promaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='email',
        ),
    ]
