# Generated by Django 5.2.1 on 2025-06-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_escola_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='promaria',
            new_name='ensino_primario',
        ),
        migrations.RenameField(
            model_name='classe',
            old_name='ciclo',
            new_name='primeiro_ciclo',
        ),
        migrations.RenameField(
            model_name='classe',
            old_name='nome',
            new_name='segundo_ciclo',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='escola',
        ),
        migrations.AddField(
            model_name='escola',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.classe'),
        ),
    ]
