# Generated by Django 5.2.1 on 2025-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_rename_promaria_classe_ensino_primario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='ensino_primario',
            field=models.CharField(blank=True, choices=[('0', '0ª'), ('1', '1ª'), ('2', '2ª'), ('3', '3ª'), ('4', '4ª'), ('5', '5ª'), ('6', '6ª')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='primeiro_ciclo',
            field=models.CharField(blank=True, choices=[('7', '7ª'), ('8', '8ª'), ('9', '9ª')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='segundo_ciclo',
            field=models.CharField(blank=True, choices=[('10', '10ª'), ('11', '11ª'), ('12', '12ª'), ('13', '13ª')], max_length=2, null=True),
        ),
    ]
