# Generated by Django 5.2.1 on 2025-06-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_alter_classe_ensino_primario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='classe',
        ),
        migrations.AddField(
            model_name='escola',
            name='classes',
            field=models.ManyToManyField(blank=True, to='school.classe'),
        ),
    ]
