# Generated by Django 5.2.1 on 2025-06-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_remove_escola_classe_escola_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='tipo_escola',
            field=models.CharField(choices=[('EP', 'Ensino Primário'), ('PC', 'Primeiro Ciclo '), ('SC', 'Segundo Ciclo')], max_length=2),
        ),
    ]
