# Generated by Django 5.2.1 on 2025-06-23 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_alter_escola_tipo_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.anoletivo'),
        ),
    ]
