# Generated by Django 5.2.1 on 2025-06-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_anoletivo_alter_turma_ano_lectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestreliberado',
            name='trimestre',
            field=models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')]),
        ),
    ]
