# Generated by Django 5.2.1 on 2025-06-28 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_alter_trimestreliberado_trimestre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('c', 'Certificado'), ('d', 'Declaração'), ('h', 'Histórico')], max_length=1)),
                ('status', models.CharField(choices=[('p', 'Pendente'), ('a', 'Aprovado'), ('r', 'Rejeitado')], default='p', max_length=1)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.aluno')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
