# Generated by Django 5.2.3 on 2025-06-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_pedidodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorDisciplinaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.turma')),
            ],
            options={
                'unique_together': {('professor', 'disciplina', 'turma')},
            },
        ),
    ]
