# Generated by Django 5.2.3 on 2025-06-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_professordisciplinaturma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minipauta',
            name='assiduidade',
        ),
        migrations.RemoveField(
            model_name='minipauta',
            name='comportamento',
        ),
        migrations.RemoveField(
            model_name='minipauta',
            name='faltas',
        ),
        migrations.DeleteModel(
            name='ProfessorDisciplinaTurma',
        ),
    ]
