# Generated by Django 5.2.3 on 2025-07-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_disciplinalecionada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disciplinalecionada',
            unique_together={('professor', 'turma')},
        ),
        migrations.RemoveField(
            model_name='disciplinalecionada',
            name='disciplina',
        ),
    ]
