# Generated by Django 5.2.3 on 2025-07-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_alter_disciplinalecionada_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disciplinalecionada',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='disciplinalecionada',
            name='turma',
        ),
        migrations.AddField(
            model_name='disciplinalecionada',
            name='turma',
            field=models.ManyToManyField(to='school.turma'),
        ),
    ]
