# Generated by Django 5.2.3 on 2025-07-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_alter_disciplinalecionada_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='disciplinalecionada',
            name='disciplina',
            field=models.ManyToManyField(to='school.disciplina'),
        ),
    ]
