# Generated by Django 5.2.3 on 2025-07-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_remove_professor_disciplina_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisciplinaLecionada',
        ),
    ]
