# Generated by Django 5.2.3 on 2025-07-04 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_delete_disciplinalecionada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaLecionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.professor')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.turma')),
            ],
            options={
                'db_table': 'DisciplinaLecionada',
                'unique_together': {('turma', 'disciplina')},
            },
        ),
    ]
