# Generated by Django 5.2.3 on 2025-07-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_disciplinalecionada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assiduidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_saida', models.TimeField()),
                ('cargo', models.CharField(choices=[('Professor', 'Professor'), ('Coordenador', 'Coordenador')], max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assiduidades', to='school.coordenador')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assiduidades', to='school.professor')),
            ],
            options={
                'verbose_name': 'Registro de Assiduidade',
                'verbose_name_plural': 'Registros de Assiduidade',
                'ordering': ['-data', 'hora_entrada'],
            },
        ),
    ]
