# Generated by Django 5.2.3 on 2025-07-06 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_assiduidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('P', 'Professor'), ('C', 'Coordenador')], max_length=1)),
                ('usuario_id', models.PositiveIntegerField()),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('P', 'Professor'), ('C', 'Coordenador')], max_length=1)),
                ('usuario_id', models.PositiveIntegerField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField()),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
