# Generated by Django 5.2.3 on 2025-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='tipo',
            field=models.CharField(choices=[('P', 'Professor'), ('C', 'Coordenador')], max_length=10),
        ),
    ]
