# Generated by Django 5.2.3 on 2025-07-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_alter_ponto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='tipo',
            field=models.CharField(choices=[('P', 'Professor'), ('C', 'Coordenador')], max_length=15),
        ),
    ]
