# Generated by Django 5.2.3 on 2025-07-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_alter_ponto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='usuario_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
