# Generated by Django 5.2.3 on 2025-07-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_alter_ponto_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='tipo',
            field=models.CharField(choices=[('P', 'Professor'), ('C', 'Coordenador')], max_length=15),
        ),
    ]
