# Generated by Django 5.2.3 on 2025-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_alter_desempenho_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='tipo',
            field=models.CharField(choices=[('P', 'Professor'), ('C', 'Coordenador')], max_length=1),
        ),
    ]
