# Generated by Django 5.2.3 on 2025-07-07 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_alter_ponto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaElaborada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('tema', models.CharField(max_length=255)),
                ('objetivos', models.TextField()),
                ('conteudo', models.TextField()),
                ('metodologia', models.TextField()),
                ('recursos', models.TextField()),
                ('avaliacao', models.TextField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.turma')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
