# Generated by Django 5.2.3 on 2025-07-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_aulaelaborada'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaelaborada',
            name='subtema',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
