# Generated by Django 5.2.3 on 2025-07-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0058_horario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diretor',
            table='Diretor',
        ),
        migrations.AlterModelTable(
            name='disciplina',
            table='Disciplina',
        ),
    ]
