# Generated by Django 5.2.3 on 2025-07-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_alter_diretor_table_alter_disciplina_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='user',
        ),
    ]
