# Generated by Django 5.2.3 on 2025-07-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_remove_escola_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='ano_fundacao',
        ),
    ]
